[supervisord]
nodaemon=true
user=www-data
logfile=/var/www/storage/logs/supervisord.log

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autostart=true
autorestart=true

[program:queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --tries=3 --sleep=5
directory=/var/www
user=www-data
autostart=true
autorestart=true
redirect_stderr=true

[program:laravel-scheduler]
command=bash -c "while true; do php artisan schedule:run --no-interaction; sleep 60; done"
directory=/var/www
user=www-data
autostart=true
autorestart=true
redirect_stderr=true
