# Rate limit per IP (allows more throughput while still protecting from abuse)
    limit_req_zone $binary_remote_addr zone=one:10m rate=15r/s;
server {
    listen 80;
    server_name localhost;

    root /var/www/public;
    index index.php index.html;

    client_max_body_size 100M;

    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    large_client_header_buffers 4 64k;

    # Serve Vite assets
    location /build/ {
        alias /var/www/public/build/;
        try_files $uri $uri/ =404;
        access_log off;
        log_not_found off;
    }

    # Laravel routes
    location / {
        limit_req zone=one burst=30 nodelay;
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass ffd_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    # Block sensitive files
    location ~ /\.(?!well-known).* {
        deny all;
    }

    access_log off;
    error_log off;
}
