# Staging: Docker Nginx — dev.fixedservices.ethiotelecom.et (proxy to app:9000)

server {
    listen 80;
    server_name localhost dev.fixedservices.ethiotelecom.et;

    root /var/www/public;
    index index.php index.html;
    client_max_body_size 100M;
    large_client_header_buffers 4 64k;

    location /build/ {
        alias /var/www/public/build/;
        try_files $uri $uri/ =404;
        access_log off;
        log_not_found off;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass fbb_staging_app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;

        fastcgi_param HTTP_X_FORWARDED_PROTO $http_x_forwarded_proto;
        fastcgi_param HTTP_X_FORWARDED_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_FOR $proxy_add_x_forwarded_for;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    access_log on;
    error_log on;
}
