server {
    listen 80;
    server_name fixedservices.ethiotelecom.et;

    root /var/www/public;
    index index.php index.html;

    # Upload limit
    client_max_body_size 100M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /storage/ {
        alias /var/www/public/storage/;
        log_not_found off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Increase FastCGI buffers to handle large headers
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
    }

    access_log off;
}
